### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [willyii/CS217-RayTracing#7]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm building your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/117318125-b7764c00-aebc-11eb-9301-150da3929f37.png)

thank you  
best regards to you  
William

**Comment by willyii** [comment]
Hi, I remove the key word "static const" from the file "object.h". I guess the problem is from the initialize the constant in GPU. I do have the GPU machine next to me these days. Pls use the updated code to see if it compile or not. 

Pls let me know if these issue solved or not #

**Comment by willyii** [comment]
Verified, can be solved by above method
