### ISSUE TITLE
the scene pictures are  black

### ISSUE THREAD

**Issue by WilliamWangPeng** [willyii/CS217-RayTracing#8]
Hi dear author,  
    Thank you for your kindness :100:  
    Compiling is ok now, but images in the result fold are black,.      
    

![image](https://user-images.githubusercontent.com/51076736/118403274-4f83ea80-b6a0-11eb-9b1c-e225bf7d3639.png)

thank you  
best regards  
William

**Comment by willyii** [comment]
Hello, I just fix it. It might because I remove the "const" key word of small_t. I add it back. 

If it still not work, pls change to "cuda" branch and see if it work. If "cuda" branch cannot work neither, pls let me know.

**Comment by willyii** [comment]
Runs ok in my machine. Close it
